In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv(r'C:\\Users\\Arjun Singh Tomar\\Downloads\\day1_ml_practice_dataset.csv')

In [4]:
df.head()

,student_id,age,gender,city,salary,study_hours,attendance_pct,placed
0,1001,20,Male,Delhi,85000.0,2.0,78.0,1
1,1002,22,Female,Mumbai,92000.0,3.0,85.0,1
2,1003,25,Male,Delhi,70000.0,1.0,62.0,0
3,1004,21,Female,Pune,65000.0,2.0,74.0,1
4,1005,29,Male,Bangalore,120000.0,5.0,91.0,1

In [7]:
df.tail()

,student_id,age,gender,city,salary,study_hours,attendance_pct,placed
21,1022,23,Female,Pune,74000.0,2.0,77.0,1
22,1023,28,Male,Bangalore,108000.0,4.0,89.0,1
23,1024,32,Female,Delhi,93000.0,2.0,69.0,0
24,1025,25,Male,Mumbai,79000.0,3.0,75.0,1
25,1025,25,Male,Mumbai,79000.0,3.0,75.0,1

In [9]:
df.sample()

,student_id,age,gender,city,salary,study_hours,attendance_pct,placed
18,1019,21,Male,Bangalore,68000.0,1.0,60.0,0

In [10]:
df.isnull().sum()

student_id        0
age               0
gender            0
city              0
salary            1
study_hours       1
attendance_pct    1
placed            0
dtype: int64

In [18]:
df.fillna(df['salary'].mean)

,student_id,age,gender,city,salary,study_hours,attendance_pct,placed
0,1001,20,Male,Delhi,85000.0,2.0,78.0,1
1,1002,22,Female,Mumbai,92000.0,3.0,85.0,1
2,1003,25,Male,Delhi,70000.0,1.0,62.0,0
3,1004,21,Female,Pune,65000.0,2.0,74.0,1
4,1005,29,Male,Bangalore,120000.0,5.0,91.0,1
5,1006,24,Female,Delhi,<bound method Series.mean of 0 85000.0\n1...,3.0,80.0,1
6,1007,31,Male,Mumbai,95000.0,4.0,68.0,0
7,1008,27,Female,Pune,78000.0,<bound method Series.mean of 0 85000.0\n1...,72.0,0
8,1009,23,Male,Delhi,71000.0,2.0,<bound method Series.mean of 0 85000.0\n1...,1
9,1010,26,Female,Bangalore,110000.0,4.0,88.0,1
10,1011,30,Male,Mumbai,99000.0,3.0,65.0,0
11,1012,28,Female,Delhi,87000.0,2.0,79.0,1
12,1013,25,Male,Pune,73000.0,1.0,58.0,0
13,1014,22,Female,Bangalore,105000.0,4.0,90.0,1
14,1015,33,Male,Delhi,115000.0,5.0,55.0,0
15,1016,24,Female,Mumbai,82000.0,2.0,81.0,1
16,1017,27,Male,Pune,76000.0,3.0,70.0,0
17,1018,29,Female,Delhi,91000.0,3.0,84.0,1
18,1019,21,Male,Bangalore,68000.0,1.0,60.0,0
19,1020,26,Female,Mumbai,98000.0,4.0,86.0,1
20,1021,30,Male,Delhi,102000.0,3.0,73.0,0
21,1022,23,Female,Pune,74000.0,2.0,77.0,1
22,1023,28,Male,Bangalore,108000.0,4.0,89.0,1
23,1024,32,Female,Delhi,93000.0,2.0,69.0,0
24,1025,25,Male,Mumbai,79000.0,3.0,75.0,1
25,1025,25,Male,Mumbai,79000.0,3.0,75.0,1

In [15]:
df.isnull().sum()

student_id        0
age               0
gender            0
city              0
salary            1
study_hours       1
attendance_pct    1
placed            0
dtype: int64

# Numpy Revision

In [20]:
arr = np.array([10,20,30,40])

In [21]:
print(arr)

[10 20 30 40]

In [23]:
arr.shape

(4,)

In [25]:
arr.size

4

In [28]:
arr.ndim

1

In [29]:
arr.dtype

dtype('int64')

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.random.rand(7)

array([0.42640617, 0.79767488, 0.90141895, 0.47238812, 0.50681839,
       0.21144876, 0.34567311])

In [37]:
arr.mean()

np.float64(25.0)

In [38]:
np.median(arr)

np.float64(25.0)

In [40]:
arr.min()

np.int64(10)

In [41]:
arr.max()

np.int64(40)

In [44]:
arr.std()

np.float64(11.180339887498949)

# Indexing and Slicing

In [45]:
arr[0]

np.int64(10)

In [46]:
arr[3]

np.int64(40)

In [47]:
arr[1:4]

array([20, 30, 40])

In [48]:
arr[0:3]

array([10, 20, 30])

In [50]:
arr[::]

array([10, 20, 30, 40])

In [51]:
arr2 = np.array([[10,20,30,40],[50,60,70,80]])

In [52]:
print(arr2)

[[10 20 30 40]
 [50 60 70 80]]

In [55]:
arr2[1,2]

np.int64(70)

In [60]:
arr2[1,3]

np.int64(80)

# Array operation

In [69]:
a = np.array([1,2,3,4,5])

In [70]:
b = np.array([6,7,8,9,10])

In [71]:
c = a+b

In [72]:
print(c)

[ 7  9 11 13 15]

In [73]:
d = a-b

In [74]:
print(d)

[-5 -5 -5 -5 -5]

In [75]:
print(a*b)
print(a/b)
print(a%b)

[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]

# Statistical

In [76]:
arr2.mean()

np.float64(45.0)

In [77]:
np.median(arr2)

np.float64(45.0)

# Reshaping

In [85]:
arr = np.arange(1,13)

In [86]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [87]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [89]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Axis

In [90]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [91]:
np.sum(arr)

np.int64(21)

In [93]:
np.sum(arr,axis=1) # row wise sum

array([ 6, 15])

In [94]:
np.sum(arr,axis=0) # column wise sum

array([5, 7, 9])

# Boolean

In [95]:
arr = np.array([10,20,30,40,50,60])

In [97]:
print(arr)

[10 20 30 40 50 60]

In [98]:
arr>25

array([False, False,  True,  True,  True,  True])

# Copy

In [99]:
arr = np.array([1,2,3,4,5])

In [100]:
arr2 = arr

In [101]:
print(arr2)

[1 2 3 4 5]

In [102]:
arr2 = arr.copy()

In [103]:
arr2

array([1, 2, 3, 4, 5])

# Prcatice question with a Array

In [104]:


marks = np.array([
    [80, 75, 90],
    [60, 70, 65],
    [95, 88, 92],
    [55, 60, 58],
    [85, 90, 87]
])

In [105]:
marks.shape

(5, 3)

In [107]:
marks.ndim

2

In [108]:
np.average(marks)

np.float64(76.66666666666667)

In [109]:
np.average(marks,axis=1)

array([81.66666667, 65.        , 91.66666667, 57.66666667, 87.33333333])

In [110]:
np.average(marks,axis = 0)

array([75. , 76.6, 78.4])

In [111]:
marks.max()

np.int64(95)

In [112]:
marks.min()

np.int64(55)

In [122]:
a = np.average(marks)

In [124]:
np.sort(marks,axis=0)

array([[55, 60, 58],
       [60, 70, 65],
       [80, 75, 87],
       [85, 88, 90],
       [95, 90, 92]])