# Pandas Revision

In [1]:
import pandas as pd

In [9]:
df = pd.read_csv(r'C:\\Users\\Arjun Singh Tomar\\Downloads\\employe salary\\Employee_Salary_Dataset.csv')

In [10]:
df.head()

   ID  Experience_Years  Age  Gender  Salary
0   1                 5   28  Female  250000
1   2                 1   21    Male   50000
2   3                 3   23  Female  170000
3   4                 2   22    Male   25000
4   5                 1   17    Male   10000

In [11]:
df.tail()

    ID  Experience_Years  Age  Gender   Salary
30  31                10   34    Male    80000
31  32                15   54    Male   900000
32  33                20   55  Female  1540000
33  34                19   53  Female  9300000
34  35                16   49    Male  7600000

In [12]:
df.shape

(35, 5)

In [14]:
df.sample(5)

    ID  Experience_Years  Age  Gender   Salary
30  31                10   34    Male    80000
29  30                 2   21  Female     6100
13  14                11   40    Male   220100
26  27                 1   18    Male     3000
5    6                25   62    Male  5001000

In [16]:
df.dtypes

ID                   int64
Experience_Years     int64
Age                  int64
Gender              object
Salary               int64
dtype: object

In [17]:
df.columns

Index(['ID', 'Experience_Years', 'Age', 'Gender', 'Salary'], dtype='object')

In [19]:
df.describe()

              ID  Experience_Years        Age        Salary
count  35.000000          35.00000  35.000000  3.500000e+01
mean   18.000000           9.20000  35.485714  2.059147e+06
std    10.246951           7.55295  14.643552  3.170124e+06
min     1.000000           1.00000  17.000000  3.000000e+03
25%     9.500000           2.50000  22.500000  2.250000e+04
50%    18.000000           6.00000  29.000000  2.500000e+05
75%    26.500000          15.00000  53.500000  3.270000e+06
max    35.000000          27.00000  62.000000  1.000000e+07

In [21]:
df.nunique()

ID                  35
Experience_Years    15
Age                 18
Gender               2
Salary              33
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [28]:
a = df["Age"]

In [31]:
print(a)

0     28
1     21
2     23
3     22
4     17
5     62
6     54
7     21
8     36
9     54
10    26
11    29
12    39
13    40
14    23
15    27
16    34
17    54
18    21
19    36
20    54
21    26
22    29
23    21
24    23
25    22
26    18
27    62
28    54
29    21
30    34
31    54
32    55
33    53
34    49
Name: Age, dtype: int64

In [34]:
df[["Age", "Salary"]]

    Age    Salary
0    28    250000
1    21     50000
2    23    170000
3    22     25000
4    17     10000
5    62   5001000
6    54    800000
7    21      9000
8    36     61500
9    54    650000
10   26    250000
11   29   1400000
12   39   6000050
13   40    220100
14   23      7500
15   27     87000
16   34    930000
17   54   7900000
18   21     15000
19   36    330000
20   54   6570000
21   26     25000
22   29   6845000
23   21      6000
24   23      8900
25   22     20000
26   18      3000
27   62  10000000
28   54   5000000
29   21      6100
30   34     80000
31   54    900000
32   55   1540000
33   53   9300000
34   49   7600000

In [39]:
df.loc[0:5, ["Age", "Salary"]]

   Age   Salary
0   28   250000
1   21    50000
2   23   170000
3   22    25000
4   17    10000
5   62  5001000

In [40]:
df.iloc[2:3,2:4]

   Age  Gender
2   23  Female

In [46]:
df = df.drop('ID',axis=1)

In [47]:
df.sample()

    Experience_Years  Age  Gender  Salary
16                10   34  Female  930000

In [49]:
df[df["Age"]>25]

    Experience_Years  Age  Gender    Salary
0                  5   28  Female    250000
5                 25   62    Male   5001000
6                 19   54  Female    800000
8                 10   36  Female     61500
9                 15   54  Female    650000
10                 4   26  Female    250000
11                 6   29    Male   1400000
12                14   39    Male   6000050
13                11   40    Male    220100
15                 4   27  Female     87000
16                10   34  Female    930000
17                15   54  Female   7900000
19                10   36    Male    330000
20                15   54    Male   6570000
21                 4   26    Male     25000
22                 5   29    Male   6845000
27                27   62  Female  10000000
28                19   54  Female   5000000
30                10   34    Male     80000
31                15   54    Male    900000
32                20   55  Female   1540000
33                19   53  Female   9300000
34                16   49    Male   7600000

In [50]:
df[df['Salary']>700000]

    Experience_Years  Age  Gender    Salary
5                 25   62    Male   5001000
6                 19   54  Female    800000
11                 6   29    Male   1400000
12                14   39    Male   6000050
16                10   34  Female    930000
17                15   54  Female   7900000
20                15   54    Male   6570000
22                 5   29    Male   6845000
27                27   62  Female  10000000
28                19   54  Female   5000000
31                15   54    Male    900000
32                20   55  Female   1540000
33                19   53  Female   9300000
34                16   49    Male   7600000

# Missing Values

In [52]:
df.isnull().sum()

Experience_Years    0
Age                 0
Gender              0
Salary              0
dtype: int64

# Duplicate

In [53]:
df.duplicated().sum()

np.int64(0)

# Sorting

In [55]:
df.sort_values("Salary",ascending=False)

    Experience_Years  Age  Gender    Salary
27                27   62  Female  10000000
33                19   53  Female   9300000
17                15   54  Female   7900000
34                16   49    Male   7600000
22                 5   29    Male   6845000
20                15   54    Male   6570000
12                14   39    Male   6000050
5                 25   62    Male   5001000
28                19   54  Female   5000000
32                20   55  Female   1540000
11                 6   29    Male   1400000
16                10   34  Female    930000
31                15   54    Male    900000
6                 19   54  Female    800000
9                 15   54  Female    650000
19                10   36    Male    330000
0                  5   28  Female    250000
10                 4   26  Female    250000
13                11   40    Male    220100
2                  3   23  Female    170000
15                 4   27  Female     87000
30                10   34    Male     80000
8                 10   36  Female     61500
1                  1   21    Male     50000
21                 4   26    Male     25000
3                  2   22    Male     25000
25                 3   22  Female     20000
18                 2   21    Male     15000
4                  1   17    Male     10000
7                  2   21  Female      9000
24                 4   23  Female      8900
14                 2   23    Male      7500
29                 2   21  Female      6100
23                 1   21  Female      6000
26                 1   18    Male      3000

In [56]:
df.groupby("Age")["Salary"].mean()

Age
17    1.000000e+04
18    3.000000e+03
21    1.722000e+04
22    2.250000e+04
23    6.213333e+04
26    1.375000e+05
27    8.700000e+04
28    2.500000e+05
29    4.122500e+06
34    5.050000e+05
36    1.957500e+05
39    6.000050e+06
40    2.201000e+05
49    7.600000e+06
53    9.300000e+06
54    3.636667e+06
55    1.540000e+06
62    7.500500e+06
Name: Salary, dtype: float64

In [57]:
df["Age"] = df["Age"].apply(lambda x: x + 1)

In [58]:
df.head()

   Experience_Years  Age  Gender  Salary
0                 5   29  Female  250000
1                 1   22    Male   50000
2                 3   24  Female  170000
3                 2   23    Male   25000
4                 1   18    Male   10000

# Value Counts

In [60]:
df["Gender"].value_counts()

Gender
Female    18
Male      17
Name: count, dtype: int64